# render.yaml
services:
  - type: web
    name: sistema-osiris
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    rootDirectory: .
    publishDirectory: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: OSIRIS_MODE
        value: vigilancia_total
